[sub]
; 基础设置
emoji = true
append_type = true
sort = false
udp = true
tfo = false
scv = false
fdn = false
new_name = true

[rule_providers]
; 这里对应你提供的 rule-providers
reject = http,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt,domain,,86400
direct = http,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt,domain,,86400
pro = http,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt,domain,,86400
private = http,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt,domain,,86400
cncidr = http,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt,ipcidr,,86400
anime-trackers = http,https://raw.githubusercontent.com/Pioooooo/clash-rules-bt/main/anime_trackers.txt,domain,,86400
applications = http,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt,classical,,86400

[rules]
; 自定义规则
DOMAIN-SUFFIX,steamcontent.com,DIRECT
DOMAIN,steamcdn-a.akamaihd.net,DIRECT
DOMAIN-SUFFIX,steamstatic.com,DIRECT
DOMAIN-SUFFIX,jsdelivr.net,DIRECT
DOMAIN-SUFFIX,mikanani.me,Proxy

; 引用上面定义的 providers
RULE-SET,private,DIRECT
RULE-SET,direct,DIRECT
RULE-SET,pro,Proxy
RULE-SET,cncidr,DIRECT
RULE-SET,applications,DIRECT
RULE-SET,anime-trackers,Proxy

; 兜底规则
GEOIP,LAN,DIRECT
GEOIP,CN,DIRECT
MATCH,Proxy