name = "sub-converter-worker"
main = "worker.js"
compatibility_date = "2024-04-18"

# --- 线上部署配置（默认） ---
# 这里不写任何 vars 和 kv_namespaces
# 这样每次部署时，Cloudflare 就会乖乖去读取你在网页后台设置的值，绝不会被覆盖！

# --- 本地测试配置（dev 环境） ---
[env.dev.vars]
BACKEND = "https://api.wcc.best"

[[env.dev.kv_namespaces]]
binding = "SUB_BUCKET"
preview_id = "test-local-kv"
id = "test-local-kv"
